# PostgreSQL configuration for blockchain-service database.

apiVersion: v1
kind: ConfigMap
metadata:
  name: blockchain-postgres-config
  namespace: blockchain-postgres
  labels:
    app.kubernetes.io/name:      blockchain-postgres
    app.kubernetes.io/component: config
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
