# PostgreSQL credentials for blockchain-service database.

apiVersion: v1
kind: Secret
metadata:
  name: blockchain-postgres-secret
  namespace: blockchain-postgres
  labels:
    app.kubernetes.io/name:      blockchain-postgres
    app.kubernetes.io/component: secret
type: Opaque
data:
  POSTGRES_USER:     cG9zdGdyZXM=
  POSTGRES_PASSWORD: R2o0MlJZMkk4TzQw
  POSTGRES_DB:       YmxvY2tjaGFpbl9kYg==
