# PostgreSQL credentials for blockchain-service.

apiVersion: v1
kind: Secret
metadata:
  name: blockchain-postgres-secret
  namespace: blockchain-postgres
  labels:
    app.kubernetes.io/name:      blockchain-postgres
    app.kubernetes.io/component: secret
type: Opaque
data:
  POSTGRES_USER: YmxvY2tjaGFpbl91c2Vy
  POSTGRES_PASSWORD: dmVyeVN0cm9uZ0Jsb2NrY2hhaW5QYXNz
  POSTGRES_DB: YmxvY2tjaGFpbl9kYg==
