apiVersion: v1
kind: Service
metadata:
  name: blockchain-postgres-headless
  namespace: blockchain-postgres
  labels:
    app.kubernetes.io/name: blockchain-postgres
    app.kubernetes.io/component: database-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: blockchain-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: blockchain-postgres
  namespace: blockchain-postgres
  labels:
    app.kubernetes.io/name: blockchain-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  selector:
    app: blockchain-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP