apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blockchain-db
  namespace: blockchain-network
spec:
  serviceName: blockchain-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-db
  template:
    metadata:
      labels:
        app: blockchain-db
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - configMapRef:
                name: blockchain-db-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: blockchain-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blockchain-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: blockchain-db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi # Kapasitas lebih besar untuk data blockchain
